name: Build cockpit-zfs (Debian bookworm)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
      - name: Prepare APT & install build deps
        shell: bash
        run: |
          set -euxo pipefail
          export DEBIAN_FRONTEND=noninteractive
          # Enable contrib (ZFS userspace lives here on Debian)
          sed -i 's/ main$/ main contrib/' /etc/apt/sources.list || true
          apt-get update
          apt-get install -y --no-install-recommends \
            git ca-certificates curl make build-essential pkg-config \
            python3 python3-dev python3-pip cython3 \
            zfsutils-linux libzfslinux-dev python3-libzfs \
            nodejs npm jq moreutils yarnpkg cockpit
          # Your requested symlink (container runs as root, so no sudo needed)
          ln -sf /usr/bin/yarnpkg /usr/local/bin/yarn

      - name: Checkout 45Drives/cockpit-zfs (recursive)
        uses: actions/checkout@v4
        with:
          repository: 45Drives/cockpit-zfs
          submodules: recursive
          fetch-depth: 0

      - name: Build
        shell: bash
        run: |
          set -euxo pipefail
          make

      # Install into a staging directory so we can publish an artifact
      # (If you truly want "sudo make install" to the container root, see note below.)
      - name: Install to staging (DESTDIR)
        shell: bash
        run: |
          set -euxo pipefail
          make install DESTDIR="$PWD/out" PREFIX=/usr

      - name: Pack artifact
        shell: bash
        run: |
          set -euxo pipefail
          tar -C out -czf cockpit-zfs-bookworm.tar.gz .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cockpit-zfs-bookworm
          path: cockpit-zfs-bookworm.tar.gz
          if-no-files-found: error
